---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gemfire-for-kubernetes-crd
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: gemfire-for-kubernetes-repository
  interval: 1m0s
  path: ./gemfire-for-kubernetes/crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gemfire-crd
      namespace: service-instances
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gemfire-for-kubernetes-operator
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: gemfire-for-kubernetes-crd
  interval: 1m0s
  path: ./gemfire-for-kubernetes/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gemfire-operator
      namespace: service-instances
