---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: image-pull-secret-export-import
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: package-and-service-instances-namespaces
  interval: 1m0s
  path: ./gemfire-for-kubernetes/image-pull-secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: image-pull-secret
      namespace: service-instances
    - apiVersion: v1
      kind: Secret
      name: image-pull-secret
      namespace: tanzu-kustomize-controller