---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sql-postgres
  namespace: postgres-system
spec:
  interval: 5m
  chart:
    spec:
      version: "v2.3.0"
      chart: vmware-sql-postgres-operator
      sourceRef:
        kind: HelmRepository
        name: sql-postgres
      interval: 60m
