---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: envoyproxy
  namespace: envoy-gateway-system
spec:
  interval: 5m
  type: "oci"
  url: oci://registry-1.docker.io/envoyproxy
