---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: envoyproxy-repository
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: ./envoy-gateway/repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmRepository
      name: envoyproxy
      namespace: service-instances
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gateway-helm-release
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: envoyproxy-repository
  interval: 1m0s
  path: ./envoy-gateway/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: gateway-helm
      namespace: service-instances
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: envoy-gateway-class
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: gateway-helm-release
  interval: 1m0s
  path: ./envoy-gateway/gateway-class
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: gateway.networking.k8s.io/v1beta1
      kind: GatewayClass
      name: envoy-gateway-class
