---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-network-credentials-export-import
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: package-and-service-instances-namespaces
  interval: 1m0s
  path: ./tanzu-network-credential
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: tanzu-network-credentials
      namespace: service-instances
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sql-postgres-repository
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tanzu-packages-cert-manager
    - name: tanzu-network-credentials-export-import
  interval: 1m0s
  path: ./sql-postgres/repository
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: HelmRepository
      name: sql-postgres
      namespace: service-instances
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sql-postgres
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: sql-postgres-repository
  interval: 1m0s
  path: ./sql-postgres/release
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: sql-postgres
      namespace: service-instances