---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gemfire-operator
  namespace: service-instances
spec:
  interval: 5m
  chart:
    spec:
      version: "2.3.0"
      chart: gemfire-operator
      sourceRef:
        kind: HelmRepository
        name: gemfire-for-kubernetes
      interval: 60m
