---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gemfire-for-kubernetes
  namespace: gemfire-system
spec:
  interval: 5m
  type: "oci"
  url: oci://registry.tanzu.vmware.com/tanzu-gemfire-for-kubernetes
  secretRef:
    name: image-pull-secret
