---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: image-pull-secret
  namespace: service-instances
spec:
  fromNamespace: default
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretImport
metadata:
  name: image-pull-secret
  namespace: tanzu-kustomize-controller
spec:
  fromNamespace: default
