---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-gitops-serviceacct
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: package-and-service-instances-namespaces
  interval: 1m0s
  path: ./base/service-accounts/
  prune: true
  sourceRef:
    kind: GitRepository
    name: gemfire-for-kubernetes-tmc
    namespace: tanzu-continuousdelivery-resources
