---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway-helm
  namespace: service-instances
spec:
  interval: 5m
  chart:
    spec:
      version: "v0.0.0-latest"
      chart: gateway-helm
      sourceRef:
        kind: HelmRepository
        name: envoyproxy
      interval: 60m
